name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - cloud-deploy
jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4       

            - name: Copy script.sh to VM
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                source: "src/script.sh"
                target: "./"

            - name: Execute script.sh in VM
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                  bash src/script.sh