name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Clone repository to VM
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                  git clone https://github.com/SandSide/myflix-videos.git 

