name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - cloud-deploy
jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: PRINT RUNNER FILES
              run: | 
                ls
                pwd

            # - name: Copy script.sh to VM
            #   run: |
            #     scp -i ${{ secrets.VM_SSH_KEY }} src/script.sh ${{secrets.VM_USERNAME}}@${{ secrets.VM_IP }}:script.sh                

            - name: Copy script.sh to VM
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                source: "/src/script.sh"
                target: "script.sh"

            # - name: Execute script.sh in VM
            #   uses: appleboy/ssh-action@master
            #   with:
            #     host: ${{ secrets.VM_IP }}
            #     username: ${{ secrets.VM_USERNAME }}
            #     key: ${{ secrets.VM_SSH_KEY }}
            #     script: |
            #       rm script.sh
            #       bash script.sh

