name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - cloud-deploy
jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Execute commands in VM via SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                  wget https://raw.githubusercontent.com/SandSide/myflix-videos/cloud-deploy/src/script.sh
                  bash script.sh

